cache:
  mount:
    - /drone/pybase

build:
  image: bjodah/bjodahimg18dev:v1.0
  environment:
    - PYTHONUSERBASE=/drone/pybase
  commands:
    - git fetch -t 2>&1 >/dev/null
    - if [ ! -d $PYTHONUSERBASE ]; then mkdir $PYTHONUSERBASE; fi
    - PYCVODES_LAPACK=lapack,blas ./scripts/ci.sh chempy
    - (cd examples/; for f in bokeh_*.py; do python3 -m bokeh html $f; done)
    - ./scripts/prepare_deploy.sh
    - PATH=/opt/miniconda3/bin:$PATH conda config --add channels bjodah  # sym, pyodesys, pyneqsys
    - PATH=/opt/miniconda3/bin:$PATH conda build --output-folder "deploy/public_html/branches/${CI_BRANCH}" conda-recipe
    - bash -c '[[ $(python setup.py --version) =~ ^[0-9]+.* ]]'
    - ./scripts/grep-for-merge-blocking-token.sh
    - ./scripts/grep-for-binary-data.sh

deploy:

  rsync:
    host: hera.physchem.kth.se
    user: chempy
    port: 22
    source: deploy/
    target: ~
    recursive: true
    delete: false
