cache:
  mount:
    - /drone/sundials-3.1
    - /drone/pybase

build:
  image: bjodah/bjodahimg18dev:v1.0
  environment:
    - SUN3BASE=/drone/sundials-3.1
    - PYTHONUSERBASE=/drone/pybase
    - PYCVODES_LAPACK=lapack,blas
    - PYCVODES_SUNDIALS_LIBS=sundials_cvodes,sundials_nvecserial,sundials_sunlinsollapackdense,sundials_sunlinsollapackband
  commands:
    - git fetch -tq
    - if [ ! -d $SUN3BASE ]; then mkdir $SUN3BASE && .ci/install_sundials-3.1.sh $SUN3BASE; fi
    - if [ ! -d $PYTHONUSERBASE ]; then mkdir $PYTHONUSERBASE; fi
    - CPATH=$SUN3BASE/include LIBRARY_PATH=$SUN3BASE/lib LD_LIBRARY_PATH=$SUN3BASE/lib ./scripts/ci.sh chempy
    - ./scripts/prepare_deploy.sh
    - PATH=/opt/miniconda3/bin:$PATH conda config --add channels bjodah  # sym, pyodesys, pyneqsys
    - PATH=/opt/miniconda3/bin:$PATH conda build --output-folder "deploy/public_html/branches/${CI_BRANCH}" conda-recipe
    - bash -c '[[ $(python3 setup.py --version) =~ ^[0-9]+.* ]]'
    - ./scripts/grep-for-merge-blocking-token.sh
    - ./scripts/grep-for-binary-data.sh


deploy:

  rsync:
    host: hera.physchem.kth.se
    user: chempy
    port: 22
    source: deploy/
    target: ~
    recursive: true
    delete: false
