cache:
  mount:
    - /drone/sundials-3.1.2
    - /drone/pybase

build:
  image: bjodah/bjodahimg18dev:v1.3
  environment:
    - SUN3BASE=/drone/sundials-3.1.2
    - PYTHONUSERBASE=/drone/pybase
  commands:
    - git fetch -tq
    - if [ ! -d $SUN3BASE ]; then .ci/get_sundials.sh 3.1.2 $SUN3BASE; fi
    - if [ ! -d $PYTHONUSERBASE ]; then mkdir $PYTHONUSERBASE; fi
    - CPATH=$SUN3BASE/include LIBRARY_PATH=$SUN3BASE/lib LD_LIBRARY_PATH=$SUN3BASE/lib ./.ci/run_ci.sh chempy
    - ./.ci/prepare_deploy.sh
    - PATH=/opt/miniconda3/bin:$PATH conda config --add channels bjodah  # sym, pyodesys, pyneqsys
    - PATH=/opt/miniconda3/bin:$PATH conda build --output-folder "deploy/public_html/branches/${CI_BRANCH}" conda-recipe
    - bash -c '[[ $(python3 setup.py --version) =~ ^[0-9]+.* ]]'
    - ./.ci/grep-for-merge-blocking-token.sh
    - ./.ci/grep-for-binary-data.sh


deploy:

  rsync:
    host: hera.physchem.kth.se
    user: chempy
    port: 22
    source: deploy/
    target: ~
    recursive: true
    delete: false
