pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./sundials-3.1.2
      - ./pyusrb
      - ./conda_packages
    volumes:
      - /tmp/cache:/cache
    ttl: 90  # liftetime in days

  install:
    image: bjodah/bjodahimg18dev:v1.4
    commands:
      - export SUN3BASE=$(pwd)/sundials-3.1.2
      - export PYTHONUSERBASE=$(pwd)/pyusrb
      - if [ ! -d $SUN3BASE ]; then .ci/get_sundials.sh 3.1.2 $SUN3BASE -DLAPACK_ENABLE:BOOL=ON -DSUNDIALS_INDEX_TYPE:STRING="int32_t" $SUN3BASE; fi
      - if [ ! -d $PYTHONUSERBASE ]; then mkdir $PYTHONUSERBASE; fi
      - export CPATH=$SUN3BASE/include
      - export LIBRARY_PATH=$SUN3BASE/lib
      - export LD_LIBRARY_PATH=$SUN3BASE/lib
      - ls $CPATH  # debug
      - python3 -m pip install --user -e .[all]
      - git fetch -tq
      - python3 setup.py sdist                    # test pip installable sdist (checks MANIFEST.in)
      - git archive -o dist/chempy-head.zip HEAD  # test pip installable zip (symlinks break)
      - mkdir -p deploy/public_html/branches/"${DRONE_BRANCH}"
      - cp dist/chempy-* deploy/public_html/branches/"${DRONE_BRANCH}"/

  test_py:
    image: bjodah/bjodahimg18dev:v1.4
    group: testing
    commands:
      - export PYTHONUSERBASE=$(pwd)/pyusrb
      - export CPATH=$(pwd)/sundials-3.1.2/include
      - export LIBRARY_PATH=$(pwd)/sundials-3.1.2/lib
      - LD_LIBRARY_PATH=$(pwd)/sundials-3.1.2/lib
      - ./scripts/run_tests.sh --cov chempy --cov-report html --slow --veryslow
      - ./scripts/coverage_badge.py htmlcov/ htmlcov/coverage.svg
      - cp -r htmlcov/ deploy/public_html/branches/"${DRONE_BRANCH}"/
      - ./.ci/grep-for-merge-blocking-token.sh
      - bash -c '[[ $(python3 setup.py --version) =~ ^[0-9]+.* ]]'

  test_sdist:
    image: bjodah/bjodahimg18dev:v1.4
    group: testing
    environment:
      - CHEMPY_DEPRECATION_FILTER=ignore
    commands:
      - git fetch -tq
      - VERSION=$(python3 setup.py --version)
      - cd deploy/public_html/branches/"${DRONE_BRANCH}"
      - python3 -m pip install chempy-$VERSION.tar.gz
      - python3 -m pytest --pyargs chempy

  test_git_archive:
    image: bjodah/bjodahimg18dev:v1.4
    group: testing
    environment:
      - CHEMPY_DEPRECATION_FILTER=ignore
    commands:
      - cd deploy/public_html/branches/"${DRONE_BRANCH}"
      - python3 -m pip install chempy-head.zip
      - python3 -m pytest --pyargs chempy

  bldconda:
    image: bjodah/bjodahimg18dev:v1.4
    group: testing
    commands:
      - export CONDA_PKGS_DIRS=$(pwd)/conda_packages
      - git fetch -tq
      - PATH=/opt/miniconda3/bin:$PATH conda config --add channels bjodah  # sym, pyodesys, pyneqsys
      - PATH=/opt/miniconda3/bin:$PATH conda build --output-folder "deploy/public_html/branches/${DRONE_BRANCH}" conda-recipe

  rendernb:
    image: bjodah/bjodahimg18dev:v1.4
    group: testing
    environment:
      - CHEMPY_DEPRECATION_FILTER=ignore
    commands:
      - export PYTHONUSERBASE=$(pwd)/pyusrb
      - export CPATH=$(pwd)/sundials-3.1.2/include
      - export LIBRARY_PATH=$(pwd)/sundials-3.1.2/lib
      - export LD_LIBRARY_PATH=$(pwd)/sundials-3.1.2/lib
      - ./scripts/render_notebooks.sh
      - ./.ci/grep-for-binary-data.sh
      - mv index.html index.ipynb.html
      - (cd examples/; for f in bokeh_*.py; do python3 -m bokeh html $f; done)
      - cp -r index.* examples/ "deploy/public_html/branches/${DRONE_BRANCH}"

  gendocs:
    image: bjodah/bjodahimg18dev:v1.4
    group: testing
    environment:
      - CHEMPY_DEPRECATION_FILTER=ignore
    commands:
      - export PYTHONUSERBASE=$(pwd)/pyusrb
      - export CPATH=$(pwd)/sundials-3.1.2/include
      - export LIBRARY_PATH=$(pwd)/sundials-3.1.2/lib
      - export LD_LIBRARY_PATH=$(pwd)/sundials-3.1.2/lib
      - ./scripts/generate_docs.sh
      - cp LICENSE doc/_build/html/
      - cp -r doc/_build/html/ "deploy/public_html/branches/${DRONE_BRANCH}"


  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./sundials-3.1.2
      - ./pyusrb
      - ./conda_packages
    volumes:
      - /tmp/cache:/cache

  deploy:
    image: drillster/drone-rsync
    hosts: [ "192.168.1.99" ]  # davycrockett.mooo.com
    port: 22
    user: chempy
    secrets: [ rsync_key ]
    source: ./deploy
    target: ~/public_html
