{% set name = "chempy" %}
{% set version = "0.6.0.dev0+git" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: ../

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy >1.7
    - scipy >=0.16.1
    - matplotlib >=1.3.1
    - sympy >=1.1.1
    - quantities >=0.12.1
    - pulp >=1.6.8
    - pyneqsys >=0.5.1
    - pyodesys >=0.11.16
    - pyparsing >=2.0.3
    - sym >=0.3.0
    - notebook
    - nbconvert

test:
  imports:
    - {{ name }}
    - {{ name }}.kinetics
    - {{ name }}.printing
    - {{ name }}.properties
    - {{ name }}.thermodynamics
    - {{ name }}.util
  requires:
    - pytest

about:
  home: https://github.com/bjodah/{{ name }}
  license: BSD 2-Clause
  license_file: LICENSE
  summary: 'Python package useful for (physical) chemistry'
  doc_url: https://bjodah.github.io/{{ name }}/latest

extra:
  recipe-maintainers:
    - bjodah
