when:
  - event: [pull_request, tag, cron, push]

steps:
  - name: rebuild-cache
    image: bjodah/bjodahimg20dot:21.8.a
    commands:
      - find ./cache-ci/ -type f -mtime +90 -exec rm {} \;
      - tar cf cache-ci.tar ./cache-ci/
      - curl -T cache-ci.tar ftp://chempy::$${ARTIFACTS_PASS}@$${FTP_SERVER}/cache/
    secrets: [ ARTIFACTS_PASS, FTP_SERVER ]
    when:
     - event: push
       repo: bjodah/chempy

  - name: deploy
    image: bjodah/bjodahimg20dot:21.8.a
    commands:
      - tar czf chempy-${CI_COMMIT_BRANCH}.tar.gz ./deploy/public_html
      - curl -T chempy-${CI_COMMIT_BRANCH}.tar.gz ftp://chempy:$${ARTIFACTS_PASS}@$${FTP_SERVER}/public_html/
    secrets: [ ARTIFACTS_PASS, FTP_SERVER ]
    when:
     - event: push
       repo: bjodah/chempy

depends_on:
  - testing

